export const employeeData = [
  {
    empId: 1,
    name: 'John Doe',
    entryTime: '08:00',
    entryGate: 'Oman Gate',
    entryDevice: 'ABCD12',
    exitTime: '17:00',
    exitGate: 'Oman Gate',
    exitDevice: 'ABCD12',
    workingTime: '9h',
  },
  {
    empId: 2,
    name: 'Jane Smith',
    entryTime: '09:00',
    entryGate: 'Muscat Gate',
    entryDevice: 'EFG001',
    exitTime: '18:00',
    exitGate: 'Muscat Gate',
    exitDevice: 'EFG001',
    workingTime: '9h',
  },
  {
    empId: 3,
    name: 'Michael Johnson',
    entryTime: '08:30',
    entryGate: 'Sohar Gate',
    entryDevice: 'HIJ002',
    exitTime: '17:30',
    exitGate: 'Sohar Gate',
    exitDevice: 'HIJ002',
    workingTime: '9h',
  },
  {
    empId: 4,
    name: 'Emily Davis',
    entryTime: '08:45',
    entryGate: 'Salalah Gate',
    entryDevice: 'KLM003',
    exitTime: '17:45',
    exitGate: 'Salalah Gate',
    exitDevice: 'KLM003',
    workingTime: '9h',
  },
  {
    empId: 5,
    name: 'David Wilson',
    entryTime: '09:15',
    entryGate: 'Nizwa Gate',
    entryDevice: 'NOP004',
    exitTime: '18:15',
    exitGate: 'Nizwa Gate',
    exitDevice: 'NOP004',
    workingTime: '9h',
  },
  {
    empId: 6,
    name: 'Sophia Brown',
    entryTime: '07:55',
    entryGate: 'Barka Gate',
    entryDevice: 'QRS005',
    exitTime: '16:55',
    exitGate: 'Barka Gate',
    exitDevice: 'QRS005',
    workingTime: '9h',
  },
  {
    empId: 7,
    name: 'Liam Martin',
    entryTime: '08:00',
    entryGate: 'Ibri Gate',
    entryDevice: 'TUV006',
    exitTime: '17:00',
    exitGate: 'Ibri Gate',
    exitDevice: 'TUV006',
    workingTime: '9h',
  },
  {
    empId: 8,
    name: 'Olivia Taylor',
    entryTime: '08:10',
    entryGate: 'Oman Gate',
    entryDevice: 'WXZ007',
    exitTime: '17:10',
    exitGate: 'Oman Gate',
    exitDevice: 'WXZ007',
    workingTime: '9h',
  },
  {
    empId: 9,
    name: 'Noah Anderson',
    entryTime: '09:00',
    entryGate: 'Muscat Gate',
    entryDevice: 'YZA008',
    exitTime: '18:00',
    exitGate: 'Muscat Gate',
    exitDevice: 'YZA008',
    workingTime: '9h',
  },
  {
    empId: 10,
    name: 'Emma Harris',
    entryTime: '08:20',
    entryGate: 'Sohar Gate',
    entryDevice: 'BCD009',
    exitTime: '17:20',
    exitGate: 'Sohar Gate',
    exitDevice: 'BCD009',
    workingTime: '9h',
  },
  {
    empId: 11,
    name: 'James Clark',
    entryTime: '08:50',
    entryGate: 'Salalah Gate',
    entryDevice: 'EFG010',
    exitTime: '17:50',
    exitGate: 'Salalah Gate',
    exitDevice: 'EFG010',
    workingTime: '9h',
  },
  {
    empId: 12,
    name: 'Charlotte Lewis',
    entryTime: '08:35',
    entryGate: 'Nizwa Gate',
    entryDevice: 'HIJ011',
    exitTime: '17:35',
    exitGate: 'Nizwa Gate',
    exitDevice: 'HIJ011',
    workingTime: '9h',
  },
  {
    empId: 13,
    name: 'Alexander Young',
    entryTime: '09:05',
    entryGate: 'Barka Gate',
    entryDevice: 'KLM012',
    exitTime: '18:05',
    exitGate: 'Barka Gate',
    exitDevice: 'KLM012',
    workingTime: '9h',
  },
  {
    empId: 14,
    name: 'Amelia Thompson',
    entryTime: '08:25',
    entryGate: 'Ibri Gate',
    entryDevice: 'NOP013',
    exitTime: '17:25',
    exitGate: 'Ibri Gate',
    exitDevice: 'NOP013',
    workingTime: '9h',
  },
  {
    empId: 15,
    name: 'Lucas Walker',
    entryTime: '08:40',
    entryGate: 'Oman Gate',
    entryDevice: 'QRS014',
    exitTime: '17:40',
    exitGate: 'Oman Gate',
    exitDevice: 'QRS014',
    workingTime: '9h',
  },
  {
    empId: 16,
    name: 'Mia Hall',
    entryTime: '08:15',
    entryGate: 'Muscat Gate',
    entryDevice: 'TUV015',
    exitTime: '17:15',
    exitGate: 'Muscat Gate',
    exitDevice: 'TUV015',
    workingTime: '9h',
  },
  {
    empId: 17,
    name: 'Benjamin King',
    entryTime: '09:10',
    entryGate: 'Sohar Gate',
    entryDevice: 'WXZ016',
    exitTime: '18:10',
    exitGate: 'Sohar Gate',
    exitDevice: 'WXZ016',
    workingTime: '9h',
  },
  {
    empId: 18,
    name: 'Isabella Wright',
    entryTime: '08:50',
    entryGate: 'Salalah Gate',
    entryDevice: 'YZA017',
    exitTime: '17:50',
    exitGate: 'Salalah Gate',
    exitDevice: 'YZA017',
    workingTime: '9h',
  },
  {
    empId: 19,
    name: 'Ethan Lopez',
    entryTime: '09:25',
    entryGate: 'Nizwa Gate',
    entryDevice: 'BCD018',
    exitTime: '18:25',
    exitGate: 'Nizwa Gate',
    exitDevice: 'BCD018',
    workingTime: '9h',
  },
  {
    empId: 20,
    name: 'Ava Hill',
    entryTime: '08:05',
    entryGate: 'Barka Gate',
    entryDevice: 'EFG019',
    exitTime: '17:05',
    exitGate: 'Barka Gate',
    exitDevice: 'EFG019',
    workingTime: '9h',
  },
  {
    empId: 21,
    name: 'William Scott',
    entryTime: '09:00',
    entryGate: 'Ibri Gate',
    entryDevice: 'HIJ020',
    exitTime: '18:00',
    exitGate: 'Ibri Gate',
    exitDevice: 'HIJ020',
    workingTime: '9h',
  },
  {
    empId: 22,
    name: 'Ella Green',
    entryTime: '08:00',
    entryGate: 'Oman Gate',
    entryDevice: 'KLM021',
    exitTime: '17:00',
    exitGate: 'Oman Gate',
    exitDevice: 'KLM021',
    workingTime: '9h',
  },
  {
    empId: 23,
    name: 'Mason Adams',
    entryTime: '08:45',
    entryGate: 'Muscat Gate',
    entryDevice: 'NOP022',
    exitTime: '17:45',
    exitGate: 'Muscat Gate',
    exitDevice: 'NOP022',
    workingTime: '9h',
  },
  {
    empId: 24,
    name: 'Harper Nelson',
    entryTime: '08:30',
    entryGate: 'Sohar Gate',
    entryDevice: 'QRS023',
    exitTime: '17:30',
    exitGate: 'Sohar Gate',
    exitDevice: 'QRS023',
    workingTime: '9h',
  },
  {
    empId: 25,
    name: 'Jack Baker',
    entryTime: '08:20',
    entryGate: 'Salalah Gate',
    entryDevice: 'TUV024',
    exitTime: '17:20',
    exitGate: 'Salalah Gate',
    exitDevice: 'TUV024',
    workingTime: '9h',
  },
];
